### ISSUE TITLE
bug: import to work with multiple files

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#10]
## Description
Importing two files only load one file.

## Reproduction Steps
1. Click [Import Data]
2. Select any Data Types
3. Upload both files with format coherent to Data Types.
4. Only display a graph list.

## Expected Behaviour 
The number of graph list should added based on the number of datasets uploaded. 

## TODO
* [x] 1. Studies the flow of upload datasets
* [x] 2. Identify the root cause of bugs
* [x] 3. Fix Import Multiple Edge List 
* [x] 4. Fix Import Multiple Json 
* [x] 5. Fix Import Node Edge List
* [x] 6. Refactor Import Sample Data
* [x] 7. Unit Test on `add-data-thunk` 
* [x] 8. Manual End to end test
