### ISSUE TITLE
Align Demo with Master 

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#101]
# Feature Request

### Description

Align demo branch with current master. The focus are import the components and update the banking API and neo4j example.

## TODO 

* [x] 1. Export necessary constants and component for example demonstrations.
* [x] 2. Refactor `type` to `kind` for every single form constants
* [x] 3. Update Banking API tabs coherent to `master`.
* [x] 4. Implement Neo4J according to design.
