### ISSUE TITLE
Convert to Monorepo

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#108]
# Enhancements

### Description

Convert existing codebase to monorepo.

### File Structure

```
motif/
├── motif-doc/     
├── motif-jupyter/ 
├── motif-core/
├── motif-demo/
```

### TODO

- [x]  ESLint Configuration
- [x]  Prettier Configuration
- [x]  Typescript Configuration in each folder.
- [x] Manage Multiple Project with Lerna
- [x] Fork Graphin and Publish as cylynx/graphin
- [x] Refactor codebase
- [x] Lerna Monorepo React version conflicts.
- [x] Modify Github Action scripts to run CI

### Additional Fixes

- [x] 1. Fix ESLint Configurations
- [x] 2. Fix Graphin's type error after upgrades.
