### ISSUE TITLE
Change from Tsdx to Vite

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#110]
### Description

Existing package bundle tools results in:

- Possess limitation upgrade to latest stable version in NPM dependency trees.
- Slow compilation time
- Prevent relies on third party build tools that lock our dependency trees.

### Describe the solution you'd like

1. Change our bundle tools to Vite to improve extensibility and customisation capabilities.
2. Upgrade Babel and Typescript version
3. Resolve existing dependency problems. 

### References

1. [Vite Documentation](https://vitejs.dev/guide/)
2. [Terser Minification Mode](https://terser.org/docs/api-reference#terser-fast-minify-mode)

### TODO 

* [x] 1. Motif Development Configuration 
* [x] 2. Motif Production Configuration 
* [x] 3. Motif Unit Test Configuration
* [x] 4, Remove unused dependencies 
* [x] 5. Verify module usability with CRA. 
* [x] 6. Prevent duplicate namespace with Vite. 
* [x] 7. Prevent `node_module` included during compilation. 
* [x] 8. Remove types error after upgrades. 
* [x] 9. Enhance CI executions
