### ISSUE TITLE
Group Edge Aggregation Not Working

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#128]
## Current Behavior

- The group edge aggregation should works on every datasets.
- Force-directed animation does not terminate when node and edges had completed expanding.
- Improve performance of using aggregation selector.

## Steps to Reproduce

1. Import `csv`
2. Choose Force Directed Layout
3. Observe the information of edges in tooltips 

## TODO 

* [x] 1. The group edge aggregation should works on every datasets.
* [x] 2. Force-directed animation does not terminate when node and edges had completed expanding.
* [x] 3. Improve performance of using aggregation selector.
* [x] 4. Aggregate information does not display correctly.
