### ISSUE TITLE
fix: graph axis label

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#17]
## Description
Take a look at kepler's implementation and d3-axis to see how we can come up with a better axis component that works with both numeric and time variable.

## Requirement

1. The axis label must be separated equivalently.
2. Display date time accurately. 

## TODO

* [x] 1. Explore better axis component
* [x] 2. Implement `NumericAxis` to prevent overlap with large numbers.
* [x] 3. Implement `DateTimeAxis` that smartly adapts depending on the time scales.
* [x] 4. Fix `VariableInspector` does not reset when data are cleaned. 
* [x] 5. Reduce unnecessary re-renders for `SelectVariable`, `Label`, `NumericAxis`, `DateTimeAxis` in `VariableInspector`
* [x] 6. Remove `Modal` warning in console. 
* [x] 7. Remove `SimpleTooltips` warning in console. 
* [x] 8. Implement `TimeAxis` to display time values. 

## References

1. [d3-axis](https://github.com/d3/d3-axis)
2. [time-slider-marker/kepler.gl](https://github.com/keplergl/kepler.gl/blob/master/src/components/common/time-slider-marker.js
)
3. [d3-scales](https://github.com/d3/d3-scale/blob/master/README.md#time-scales)
4. [Format Date Time Axis](http://www.d3noob.org/2016/09/formatting-date-time-axis-with.html)
5. [Conditional Time Format](https://bl.ocks.org/d3noob/0e276dc70bb9184727ee47d6dd06e915)
