### ISSUE TITLE
infra: automated e2e testing

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#25]
### e2e tests
1. Test that the demo app graph renders with a sample data
2. Test that the widgets show correctly (left side, top right and bottom right)

### Implementation
1. Cypress
2. Github actions

## TODO 

* [x] 1. Cypress Installation with Typescript
* [x] 2. Test Case for Import [Random Graph]
* [x] 3. Test Case for Import [Circle Graph]
* [x] 4. Test Case for Import [Random + Circle]
* [x] 5. Test Case for Import [Les Miserables]
* [x] 6. Test Case for Import [Authorship]
* [x] 7. Test Case for Import [American Airlines]
* [x] 8. Test Case for `SideNavbar`
* [x] 9. Test Case for `LayerPanel`
* [x] 10. Test Case for `OptionPanel`
* [x] 11. Test Case for `Toolbar`
* [x] 12. Test Case for `VariableInspector`
* [x] 13. Tsdx's watch compilation error.
* [x] 14. Github actions for Jest (Automation Unit Test)
* [x] 15. Github actions for Cypress (Automation e2e/System/integration Test) 

## Experiment

[Pull Request to Trigger Github Action](https://github.com/CodesAreHonest/g6-learn/pull/2)

## References
1. [Cypress CI Integration](https://docs.cypress.io/guides/guides/continuous-integration.html)
2. [React Cypress](https://github.com/cypress-io/cypress/tree/master/npm/react)
3. [Parallel Github Actions](https://gist.github.com/ArturT/3535fc24bf2fac577462b9162c12c1d6)
4. [Cypress Github Actions](https://posthog.com/blog/cypress-end-to-end-tests)
5. [Cypress Github Action's Marketplace](https://github.com/marketplace/actions/cypress-io#basic)
