### ISSUE TITLE
feat: filter panel

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#27]
## Description 

New side widget to allow users to filter data. Unlike the variable explorer, this will be a hard filter and the items will be removed from the canvas.

## Feature
- filter on node or edge properties
- different filtering options based on data type
- filter should remove object from canvas
- deleting the data should affect the filter list

## Implementation
- Use our existing VariablePicker component but allow all data types (not only numeric / time)
- For date / time / numeric variables use the existing histogram plots
- For string variables, select from a list of unique strings
- Add a filters property to the graph redux store
- Modify the graphVisible selector step to the following logic - graphFlatten → graphFiltered → graphVisible

## TODO

* [x] 1. Filter Panel
* [x] 2. DateTime / Date / Time / Numeric variables use histogram plots 
* [x] 3. String variables use multi select with unique strings option
* [x] 4. Add a `filterOptions` to `graph` redux store
* [x] 5. Modify the `graphVisible` selector step to the following logic - graphFlatten → graphFiltered → graphVisible
* [x] 6. Remove filters when ONE data layer is removed.  
* [x] 7. Remain filters when data layer is added. 
* [x] 8. Cypress e2e tests. 

## Unit Test

1. Get Graph Filtered 
2. Graph Slices

## Inspiration 

https://kepler.gl/demo/earthquakes
