### ISSUE TITLE
Tabular view not working in banking connection data

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#38]
## Description 

1. The tabular view is not working in banking connection data. 
2. Display `undefined` in **types**. 

## Steps to Reproduce 

1. Import **Banking Connection** sample data. 
2. Expand drop down in drag and drop list. 
3. Bugs appear after click on [View Node Data] and [View Edge Data] . 

## Screenshot 

<img width="927" alt="Screenshot 2021-01-11 at 3 08 03 PM" src="https://user-images.githubusercontent.com/25884538/104164915-9d0ef300-5433-11eb-8bbe-d2ee8b1db836.png">

## TODO 
* [x] 1. Fix unable to handle `undefined` data in all fields. 
* [x] 2. Use `analyzerType` instead of `type` to format rows and columns. 
* [x] 3. Prevent display numeric values in `NaN`
* [x] 4. Fix unable to format `DateTime`, `Date` and `Time` fields.
