### ISSUE TITLE
Eliminate Cyclic Dependency

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#45]
## Description 

Eliminate all the cyclic dependency in the project. 

## Detailed Description

Circular dependency could introduce unintended or unexpected consequences in the future. 

## Possible Implementation

Explore maintainable approach to scale the application. 

## References 

1. [Reducks' Github](https://github.com/alexnm/re-ducks/tree/master/example-duck)
2. [Scalable Architecture for Redux - Reducks](https://www.freecodecamp.org/news/scaling-your-redux-app-with-ducks-6115955638be/)
3. [Redux's Typescript Guide](https://github.com/piotrwitek/react-redux-typescript-guide)

## TODO 

* [x] 1. Refactor Redux store with Scalable Architecture - Reducks 
* [x] 2. Unified typings in order to prevent circular dependency. 
* [x] 3. Refactor Container component to adopt on new redux architecture.
