### ISSUE TITLE
Upgrade to Graphin 2.0

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#47]
## Description

Upgrade into Graphin@2.0.0-beta.4 in order to perform re-testing and analyse bundle size.

## Todo

- [x] Update graph structure and import requirements (2.0 follows more of a G6 structure e.g. no need for data array) #59 
- [x] Decide whether to use built-in node shape vs our current node shape #55 
- [x] Decide whether to use build-in edge shape vs our current edge shape #55 
- [x] Sync graphin canvas theme with baseui theme #56 
- [x] Update layout options to be compatible with Graphin 2.0 #58 
- [x] Map existing behaviours to 2.0 #57 

## Impediment in Graphin 

1. Node label does not work. 
2. Edge label position is not centered

### Upgrades 

* [x] 1. Configure webpack loaders to test Graphin 2.0 package

### End to End test

* [x] 1. Options Panel - Layout
* [x] 2. Options Panel - Node Styles 
* [x] 3. Options Panel - Edge Styles
* [x] 4. Toolbar - Setting Popovers 
* [x] 5. Toolbar - Legend Selection

### Jest Unit Test 

* [x] 1. Setup jest working with Webpack. 

## References

[Graphin NPM](https://www.npmjs.com/package/@antv/graphin)
