### ISSUE TITLE
Display Error Message when accessors are invalid. 

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#51]
# Feature Request

### Description

The application shall display a meaningful message when accessors are not configure correctly with the datasets during data importation. 

### Describe the solution you'd like

We can check if the accessors fields exist in the JSON datasets and prompt an invalid accessor fields error if it does not.

## TODO 

* [x] 1. Check whether CSV header match accessors. 
* [x] 2. Verify whether batch JSON's `edge` contain accessors.   
* [x] 3. Verify whether single JSON `edge` contain valid accessors.
