### ISSUE TITLE
Use Build In Node and Edge Shape

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#55]
# Feature Request

Extends based on #47 , estimated 3 working days. 

### Description

Use build in node and edge shapes in order to style the graph elements. 

### Describe the solution you'd like

- Create `nodeStyle` and `edgeStyle` objects and utilise Graphin's API in order to style the graph elements. 
- These mentioned objects are useful to applies theme.  

## Additional Context

As mentioned in https://github.com/cylynx/motif.gl/pull/60#discussion_r563479380, this tasks must able to handle the following conditions: 
- default style that maps to degree distribution 
- node color dictionary for the legend 
- allow user styles on specific node and edges 

## TODO 

* [x] 1. Create node style objects based on our themes applied with Graphin 1.x
* [x] 2. Create edge style objects based on our themes applied with Graphin 1.x

## Bugs Involved 

* [x] 1. Legend Selection - Node Style does not work. 
* [x] 2. Fix Node Styles Filter match the new implementations. 
* [x] 3. Fix Edge Styles Filter match the new implementations. 
* [x] 4. Fix Setting Popover features to match the new implementations. 

## References

1. [Build in Node and Edge's Shape Playground](https://codesandbox.io/s/graphin-playgrounds-vueb0?file=/src/App.tsx)
2. [Graphin v2 Build in Node's Doc](https://antv.vision/graphin-docs/graphin/render/element)
3. [Graphin v2 Build in Edge's Doc](https://antv.vision/graphin-docs/graphin/render/edge)
