### ISSUE TITLE
Map Existing Behaviors to 2.0

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#57]
# Feature Request

extends from #47

### TODO

* [x]  1. Register Circle Nodes 
* [x]  2.  Register Poly Edges
* [x]  3.  Register Line Edges 
* [x]  4.  Register Loop Edges 
* [x]  5.  Register Activate Relations 
* [x]  6.  Register Graphin Highlights 
* [x]  7. Tooltip display some of the style attributes due to the change in shape and how it is styled
* [x]  8. Implement Built-in Node and Edge's State 
* [x]  9. Support Icon font with Nodes in Register Circle Nodes.
* [x] 10. Use `defaultNode` and `defaultEdge` to style our graph instead of manually adding default style property into every graph elements. 
* [x] 11. Use Build-in Node and Edge Shapes instead of G6. 
* [x] 12. Multiple Click Select

## Bugs Involved

* [x] 1. Variable Inspector - Time Series Analysis highlights not working. 
* [x] 2. `originalEvent` does not found in `IG6GraphEvent` props, require to look for better types as it results in typescript compilation error. 
* [x] 3. Handle Toggle `ArrowOptions` in Register Edges behavior as Graphin doesn't possess attribute to handle arrow styles. 
* [x] 4. Setting Popover - Group Edge does not works. 
* [x] 5. Display label on default imports. 
* [x] 6. Fix Inconsistent brush select. 

## Refactor Required 
* [x] 1. Construct hook for custom behaviours 
* [x] 2. Unified our graph states with Graphin v2.0
* [x] 3. Implement Lasso Select
* [x] 4. Unified all node and edge styles in a constant object. 
* [x] 5. render x-y coordinate with presets

## Bugs By Graphin 

1. Halo will return to original shapes if size is not specified.
2. Edge Label has no position. 

### Additional Context 

1. As mentioned in https://github.com/cylynx/motif.gl/pull/61#issuecomment-768126391, the variable inspector should flag the graph element with specific states in order to prevent mouse event to interrupt the nodes' or edges' style.

### References

1. [Graphin's Types Source Code](https://github.com/antvis/Graphin/blob/master/packages/graphin/src/index.ts)
2. [Graphin's Resize Canvas Example by 山果](https://github.com/antvis/Graphin/blob/master/packages/graphin/src/behaviors/ResizeCanvas.tsx)
3. [G6 Behavior's References](https://g6.antv.vision/en/docs/manual/middle/states/custom-behavior)
