### ISSUE TITLE
Graphin 2.0 Layout Options

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#58]
# Feature Request

Extends from https://github.com/cylynx/motif.gl/issues/47, estimate two working days. 

### Description

Update layout options to be compatible with Graphin 2.0. 

### TODO 

* [x] 1. Update layout options with newest layout format. 
* [x] 2. Update type of layouts introduce by Graphin 2.0. 

### Bugs Involved 

* [x] 1. Layout does not change after set node styles. 
* [x] 2. Group Edge features in Setting Popovers not working. 
* [x] 3. Les Miserable layout does not works (should render based on x and y).
* [x] 4. America Airline layout does not works (should render based on x and y). 
* [x] 5. Graph Layout does not changes on some of the datasets. 

### References

1. [Switching Layout Example](https://antv.vision/graphin-docs/graphin/layout/switching)
