### ISSUE TITLE
Update Graph Structure and Import Requirements

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#59]
# Feature Request

Extends from https://github.com/cylynx/motif.gl/issues/47

---

### Description

Update Graph Structure and Import Requirements coherent to Graphin 2.0's format. 

### TODO

* [x] 1. Update graph structure format 
* [x] 2. Ensure consistency between import and export JSON data.

### Bugs Completed 

 * [x] 1. Graph Layout - Invalid Graph Layout formats.
 * [x] 2. Filters - Graph does not re-render after filter applied.
 * [x] 3. Sample Data - Import Random Data breaks.
 * [x] 4. Sample Data - Banking Connection Data breaks.
