### ISSUE TITLE
Save Canvas State into Local

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#71]
# Feature Request

This feature allows a user to save and load workspaces. Currently the user can already save the data json locally, but we would like to extend that functionality to save the canvas layout options as well so upon load it will be in a similar state where he last left off. 

### Description

- Should save node styles, edge styles and layout options. 
- Should keep a copy of x and y coordinate for `preset` layout.

## TODO 

* [x] 1. Save file in specific format with style configuration.
* [x] 2. Load file with specific format. 
* [x] 3. Load styles based on the last file. 
* [x] 4. Prompt confirmation whether user want to override the styles. 

## Flowchart
![import-data](https://user-images.githubusercontent.com/25884538/109605390-1091ce80-7b60-11eb-95ae-a503b49106e4.png)
