### ISSUE TITLE
Group Edge Aggregation

### ISSUE THREAD

**Issue by CodesAreHonest** [cylynx/motif.gl#76]
# Feature Request

Group Graph's edge by aggregation function. 

## Description

There are too much edges connected between nodes results in difficulty on analyse the relationship and pattern between two entity. The feature aggregate the grouping edges' metadata in order to help user identify patterns and trends in the group edges. It allow help user gain quick access to data to make better decisions.  

User shall be allow: 
1. Configure group edge options during data importation. 
2. Configure group edge aggregation preferences under data list. 

The feature will aggregate based on _String, Date, DateTime, Time and Numerical_ data types. 

## TODO 

* [x] 1. Place a table icon on the left of eye to display node/edge data.
* [x] 2. Reconstruct Datatable modal with tabs to display node/edge data, default is node. 
* [x] 3. Display Group Edges settings. 
* [x] 4. Convert DND list to Accordion. 
* [x] 5. Perform aggregation on graphs based on data types. 
* [x] 6. Options for Group Edge during import data. 
* [x] 7. Integrate global states with group edges view in graph list. 

## Bug Discovered

* [x] 1. Rapid click on toggle visibility will crash the graphin loops. 
* [x] 2. Add attribute buttons display after added new datasets. 
* [x] 3. Clicking the table will open/close the accordion
* [x] 4. The edge attributes where you can group / aggregate should be scoped to that particular dataframe and not across all. As the video shows, you get irrelevant banking attributes for the circle dataset.
* [x] 5. Highlight edges will results in error in Search Panel. 

## Enhancements 

* [x] 1. Disable group edges configuration based on availability of edges with source and targets. 
* [x] 2. Expand graph list on defaults. 
* [x] 3. Load file shall obtain the last aggregate fields into edges.
* [x] 4. Should group by case-sensitive.
* [x] 5. Display float precisions with 5sf. 
* [x] 6. Remove old implementation of Group Edges. 
* [x] 7. Apply `flex-wrap` when text is too long in edge information accordion. 
* [x] 8. Apply debounce on toggle values to prevent potential browser freeze.
